using System;

namespace Nord.Nganga.Annotations.Attributes.Html
{
  /// <summary>
  /// When applied to a GET method of a WebAPI controller, this attribute allows the injection
  /// of arbitrary HTML into the generated view.  For longer includes, the ng-include attribute
  /// is recommended.
  /// </summary>
  [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
  public class InjectHtmlInViewAttribute : Attribute
  {
    /// <summary>
    /// Position to insert HTML.  By default, after content.
    /// </summary>
    public Position HtmlPosition { get; set; }

    /// <summary>
    /// HTML to be injected
    /// </summary>
    public string Content { get; private set; }

    /// <summary>
    /// Create a new InsertHtmlInViewAttribute
    /// </summary>
    /// <param name="content"></param>
    public InjectHtmlInViewAttribute(string content)
    {
      this.Content = content;
      this.HtmlPosition = Position.AfterContent;
    }

    /// <summary>
    /// Position to insert HTML
    /// </summary>
    public enum Position
    {
      /// <summary>
      /// Before the header generated by this method
      /// </summary>
      BeforeHeader,

      /// <summary>
      /// After the header for the section generated by this method
      /// </summary>
      AfterHeader,

      /// <summary>
      /// Immediately after the &lt;form&gt; tag.
      /// </summary>
      InsideFormAtBeginning,

      /// <summary>
      /// Before the save buttons at the bottom of the form.
      /// </summary>
      BeforeSaveButtons,

      /// <summary>
      /// Immediately before the &lt;/form&gt; tag.
      /// </summary>
      InsideFormAtEnd,

      /// <summary>
      /// After the section generated by this method
      /// </summary>
      AfterContent,
    }
  }
}